extends Node
const World = preload("res://scripts/world_state.gd")
const Saves = preload("res://scripts/save_store.gd")
const Network = preload("res://scripts/session.gd")
var failures: Array = []
var checks = 0

func check(condition: bool, description: String) -> void:
	checks += 1
	if not condition:
		failures.append(description)
		printerr("FAIL: " + description)

func _ready() -> void:
	call_deferred("run")

func run() -> void:
	var w = World.new()
	w.create_world()
	w.join_player("a", "Alice")
	w.join_player("b", "Bob")
	check(w.data.players.a.money == 300, "Starting balance")
	check(not w.command("a", "add_money", "9999").is_empty() and w.data.players.a.money == 300, "Client cannot mint money")
	check(not w.command("a", "pickup", "parcel_01").is_empty(), "Pickup rejects distant player")
	w.data.players.a.pos = w.data.items.parcel_01.pos.duplicate()
	w.data.players.b.pos = w.data.items.parcel_01.pos.duplicate()
	check(w.command("a", "pickup", "parcel_01").is_empty(), "Nearby pickup succeeds")
	check(not w.command("b", "pickup", "parcel_01").is_empty(), "Concurrent pickup has only one winner")
	check(not w.command("b", "drop", "parcel_01").is_empty(), "Non-owner cannot drop parcel")
	check(not w.command("a", "complete_order", "order_01").is_empty(), "Order requires delivery distance")
	w.data.players.a.pos = World.arr(World.DELIVERY)
	check(w.command("a", "complete_order", "order_01").is_empty(), "Valid order completes")
	check(w.data.players.a.money == 550 and not w.data.players.a.inventory.has("parcel_01"), "Reward and consume are atomic")
	check(not w.command("a", "complete_order", "order_01").is_empty() and w.data.players.a.money == 550, "Duplicate reward blocked")
	w.data.players.a.pos = w.data.containers.supply_01.pos.duplicate()
	w.command("a", "take_supply", "supply_01")
	check(w.data.players.a.inventory.supplies == 1 and w.data.containers.supply_01.inventory.supplies == 11, "Container transfer conserves items")
	w.command("a", "store_supply", "supply_01")
	check(not w.data.players.a.inventory.has("supplies") and w.data.containers.supply_01.inventory.supplies == 12, "Store conserves items")
	w.data.players.a.pos = w.data.properties.depot_01.pos.duplicate()
	check(not w.command("a", "buy_property", "depot_01").is_empty(), "Cannot buy without money")
	w.data.players.a.money = 900
	check(w.command("a", "buy_property", "depot_01").is_empty() and w.data.players.a.money == 300, "Property purchase validates and deducts")
	w.data.players.a.pos = w.data.employees.employee_01.pos.duplicate()
	check(w.command("a", "hire", "employee_01").is_empty(), "Owner can hire employee")
	for i in range(1801): w.advance(1.0 / 60, {})
	check(w.data.players.a.money == 175, "Server accrues employee income")
	w.data.players.a.pos = w.data.vehicles.van_01.pos.duplicate()
	w.data.players.b.pos = w.data.vehicles.van_01.pos.duplicate()
	check(w.command("a", "vehicle", "van_01").is_empty(), "Enter vehicle")
	check(not w.command("b", "vehicle", "van_01").is_empty(), "Vehicle has one driver")
	w.leave_player("a")
	check(w.data.vehicles.van_01.driver.is_empty(), "Disconnect releases vehicle")
	w.join_player("a", "Alice renamed")
	check(w.data.players.a.money == 175 and w.data.players.a.owned.has("depot_01"), "Reconnect retains progress")
	w.data.players.a.pos = [10, 0, 10]
	w.advance(1.0 / 60, {})
	check(not w.data.players.a.alive, "Server determines death")
	check(not w.command("a", "respawn", "").is_empty(), "Respawn cooldown enforced")
	for i in range(181): w.advance(1.0 / 60, {})
	check(w.command("a", "respawn", "").is_empty() and w.data.players.a.alive, "Respawn after cooldown")
	check(w.blocked(Vector3(0, 0, -9), 0.4), "Closed door blocks movement")
	w.data.players.a.pos = [0, 0, -7]
	w.command("a", "door", "gate_01")
	check(not w.blocked(Vector3(0, 0, -9), 0.4), "Open door allows movement")
	var initial = World.new()
	initial.create_world()
	var replay = initial.data.duplicate(true)
	initial.join_player("a", "Alice")
	initial.data.players.a.pos = initial.data.items.parcel_01.pos.duplicate()
	initial.command("a", "pickup", "parcel_01")
	for event in initial.drain_events(): World.apply_event(replay, event)
	check(replay.players.a.inventory == initial.data.players.a.inventory and replay.items.parcel_01 == initial.data.items.parcel_01, "Inventory deltas reconstruct state")
	var root = OS.get_environment("AFTER_HOURS_TEST_ROOT")
	if root.is_empty(): root = "user://core-tests-" + str(Time.get_ticks_msec())
	check(Saves.write(root, "World01", w.data).is_empty(), "Save succeeds")
	var saved = Saves.read_world(root, "World01")
	check(saved.ok and saved.world.players.a.money == 175 and not saved.world.players.a.connected, "Save/load preserves durable state")
	check(Saves.write(root, "World01", w.data).is_empty(), "Second atomic save replaces existing file")
	var path = root.path_join("Saves/World01/world.sav")
	var f = FileAccess.open(path, FileAccess.WRITE)
	f.store_string("damaged")
	f.close()
	var recovered = Saves.read_world(root, "World01")
	check(recovered.ok and recovered.get("recovered", false), "Corrupt primary recovers backup")
	check(not Saves.valid_slot("../other") and not Saves.valid_slot(""), "Path traversal rejected")
	check(Network.parse_address("192.168.1.50").port == 27020, "Default port")
	check(Network.parse_address("127.0.0.1:28000").port == 28000, "Explicit port")
	check(Network.parse_address("[::1]:27020").host == "::1", "IPv6 address")
	check(Network.parse_address("localhost:0").has("error") and Network.parse_address("localhost:no").has("error"), "Invalid ports rejected")
	print("CORE TESTS: %d passed / %d total" % [checks - failures.size(), checks])
	get_tree().quit(0 if failures.is_empty() else 1)
